{
 "title": "Papyrus-integration-ori",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\".*papyrus.*\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Header latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 1, "y": 1 },
   "targets": [
    {
     "expr": "papyrus_header_latency{kubernetes_namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Latency (seconds)"
    }
   ]
  },
  {
   "title": "Central ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Header",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 1, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_header_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Header",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(papyrus_header_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"} / papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"} * 10^4) / 10^4"
    }
   ]
  },
  {
   "title": "Body",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_body_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Body",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(papyrus_body_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"} / papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"} * 10^4) / 10^4"
    }
   ]
  },
  {
   "title": "State update",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_state_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "State update",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(papyrus_state_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"} / papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"} * 10^4) / 10^4"
    }
   ]
  },
  {
   "title": "Compiled class",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 1, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_compiled_class_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Compiled class",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(papyrus_compiled_class_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"} / papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"} * 10^4) / 10^4"
    }
   ]
  },
  {
   "title": "Base layer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "papyrus_base_layer_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Base layer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor((papyrus_base_layer_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"} or vector(0)) / papyrus_central_block_marker{kubernetes_namespace=\"$namespace\", pod=\"$pod\"} * 10^4) / 10^4"
    }
   ]
  },
  { "title": "Containers resources usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Containers CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"\"}[1m])",
     "legendFormat": "{{coxntainer}}"
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$pod\", image!=\"\", container!=\"\"}) by (container, pod)"
    }
   ]
  },
  {
   "title": "Containers storage usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"} - kubelet_volume_stats_available_bytes{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Containers IO usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{image!=\"\", namespace=\"$namespace\", pod=\"$pod\"}[1m])) by (container, pod)"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total{image!=\"\", namespace=\"$namespace\", pod=\"$pod\"}[1m])) by (container, pod)"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory GB",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "container_memory_usage_bytes{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
       "legendFormat": "container_memory_usage_bytes (GB)"
      },
      {
       "expr": "container_memory_mapped_file{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
       "legendFormat": "container_memory_mapped_file (GB)"
      },
      {
       "expr": "container_memory_rss{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
       "legendFormat": "container_memory_rss (GB)"
      },
      {
       "expr": "container_memory_max_usage_bytes{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
       "legendFormat": "container_memory_max_usage_bytes (GB)"
      },
      {
       "expr": "container_memory_swap{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
       "legendFormat": "container_memory_swap (GB)"
      },
      {
       "expr": "container_spec_memory_limit_bytes{namespace=\"$Pod\", container=\"$Pod\"} / 1024 / 1024 / 1024",
       "legendFormat": "container_spec_memory_limit_bytes (GB)"
      }
     ]
    },
    {
     "title": "Gateway incoming requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "gateway_incoming_requests{kubernetes_namespace=\"$Pod\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gateway failed requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "gateway_failed_requests{kubernetes_namespace=\"$Pod\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Gateway request latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "targets": [
      {
       "expr": "gateway_request_latency_seconds_count{kubernetes_namespace=\"$Pod\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}